apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: default
  labels:
    name: nginx-service
    environment: dev
spec:
  type: LoadBalancer
  selector:
    project: eksctl
    environment: dev
    component: nginx
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80


	 

